Add an "input args" parameter when defining derivative actions.
Islandora/islandora pull request #904
Opened 2022-10-20 22:14 UTC by jasonhildebrand

* Other Relevant Links:

Related PRs:
 * https://github.com/Islandora/Alpaca/pull/91
 * https://github.com/Islandora/Crayfish/pull/172

# What does this Pull Request do?

This PR adds an "input args" parameter in derivative actions, to be used to pass additional arguments when generating image derivatives.  This fields is only exposed in the UI for image derivatives (not for other derivative types), as images are the only use case which needs this additional field.

# Background/Motivation

I wanted to use the "density" parameter in imagemagick, but this parameter only works if applied BEFORE the input stream. According to the man page (https://manpages.ubuntu.com/manpages/trusty/man1/convert.im6.1.html) there are several options which are only valid as so-called "input options".  The addition of this field makes it possible to use these parameters to adjust the conversion.  In particular, the density parameter makes it possible to generate higher-resolution JPGs from a PDF source file.

# What's new?

One field is added to the "Edit action" page for image derivatives.  

The field should not show for other derivative types (I think I got them all - I followed existing code to remove the field from their configuration forms).

Until the related Alpaca PR is merged, the addition of this field will cause alpaca to spew errors (about the new unknown field).

I think this means some kind of version constraint will need to be applied, but I don't know exactly what/how.

# How should this be tested?

It is easier to test these PRs together.  See in-depth test plan in https://github.com/Islandora/Alpaca/pull/91

# Documentation Status

* I have added some inline documentation into the Action configuration page (links to imagemagick documentation).

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/committers

2022-10-21 13:20 UTC, adam-vessey commented
Instead of introducing this at the `AbstractGenerateDerivative` level, seemingly only to remove it from all but one extending class, would it make more sense to only _implement_ in the one class? The `AbstractGenerateDerivative` class could be extended by other modules in the wild, which would then start showing this new option in contexts where it is not desirable.

Also, the addition of new plugin config should be accompanied by an update to the config schema; If this was just hitting the `generate_image_derivative` bit, then: https://github.com/Islandora/islandora/blob/2.x/modules/islandora_image/config/schema/islandora_image.schema.yml

2022-10-21 15:34 UTC, jasonhildebrand commented
That's a good suggestion, I will make that change. I'll update the config schema, too, thanks for letting me know.

peace,
Jason
________________________________
From: Adam ***@***.***>
Sent: Friday, October 21, 2022 8:20:13 AM
To: Islandora/islandora ***@***.***>
Cc: Jason Hildebrand ***@***.***>; Author ***@***.***>
Subject: Re: [Islandora/islandora] Add an "input args" parameter when defining derivative actions. (PR #904)


Instead of introducing this at the AbstractGenerateDerivative level, seemingly only to remove it from all but one extending class, would it make more sense to only implement in the one class? The AbstractGenerateDerivative class could be extended by other modules in the wild, which would then start showing this new option in contexts where it is not desirable.

Also, the addition of new plugin config should be accompanied by an update to the config schema; If this was just hitting the generate_image_derivative bit, then: https://github.com/Islandora/islandora/blob/2.x/modules/islandora_image/config/schema/islandora_image.schema.yml

—
Reply to this email directly, view it on GitHub<https://github.com/Islandora/islandora/pull/904#issuecomment-1286952771>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABYME3ULOJ3PXIEUIJ74VTDWEKKA3ANCNFSM6AAAAAARKS3CNU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-24 17:39 UTC, jasonhildebrand commented
I have made the suggested changes. including updating the config schema.

2023-07-27 19:54 UTC, rosiel commented
This will be a breaking change as it changes Islandora's "API" (not really defined, but here used to mean "the way it communicates with other systems"). I'd like to include this in the first islandora 3.x release.

2024-08-21 21:58 UTC, jasonhildebrand commented
I resolved the merge conflicts.

2024-08-22 22:50 UTC, jasonhildebrand commented
I installed phpcs locally, but when I ran it, it produced 600+ errors on IslandoraUtils.php (an order of magnitude more than the CI job showed).  Not sure what to do.

2024-08-28 17:21 UTC, adam-vessey requested changes
RE: coding standards, our CI runs: https://github.com/Islandora/islandora_ci/blob/859a92805dd8cb51646ce30cfc12f30452dbff5c/travis_scripts.sh#L16

Specifically, with the `Drupal` coding standards.

Additional details about installing the Drupal coding standards might be gleaned from that repo, or it might be more useful to reference Drupal's docs directly: https://www.drupal.org/docs/extending-drupal/contributed-modules/contributed-module-documentation/coder/installing-coder

2024-08-28 17:21 UTC, adam-vessey commented on src/IslandoraUtils.php
> +
Fair number of things in this chunk, from: https://github.com/Islandora/islandora/actions/runs/10498083873/job/29082307172?pr=904

```
 FILE: /home/runner/work/islandora/islandora/build_dir/src/IslandoraUtils.php
--------------------------------------------------------------------------------
FOUND 47 ERRORS AND 3 WARNINGS AFFECTING 20 LINES
--------------------------------------------------------------------------------
 772 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 772 | WARNING | [ ] Line exceeds 80 characters; contains 113 characters
 773 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 773 | ERROR   | [ ] Doc comment short description must be on a single line,
     |         |     further text should be a separate paragraph
 774 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 775 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 775 | WARNING | [ ] Line exceeds 80 characters; contains 96 characters
 776 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 776 | WARNING | [ ] Line exceeds 80 characters; contains 96 characters
 777 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 778 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 778 | ERROR   | [ ] Missing parameter comment
 779 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 779 | ERROR   | [ ] Missing parameter comment
 780 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 780 | ERROR   | [ ] Missing parameter comment
 781 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 782 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 783 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 784 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 784 | ERROR   | [x] Return comment indentation must be 3 spaces, found 1
     |         |     spaces
 785 | ERROR   | [x] Expected 3 space(s) before asterisk; 4 found
 786 | ERROR   | [x] Visibility must be declared on method "array_insert_after"
 786 | ERROR   | [ ] Method name "IslandoraUtils::array_insert_after" is not in
     |         |     lowerCamel format
 786 | ERROR   | [x] Expected 0 spaces after opening parenthesis; 1 found
 786 | ERROR   | [x] There should be no white space after an opening "("
 786 | ERROR   | [x] There should be no white space before a closing ")"
 786 | ERROR   | [x] Expected 0 spaces before closing parenthesis; 1 found
 787 | ERROR   | [x] Spaces must be used to indent lines; tabs are not allowed
 787 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 3
 787 | ERROR   | [x] There should be no white space after an opening "("
 787 | ERROR   | [x] There should be no white space before a closing ")"
 788 | ERROR   | [x] Spaces must be used to indent lines; tabs are not allowed
 788 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 3
 788 | ERROR   | [x] There should be no white space after an opening "("
 788 | ERROR   | [x] There should be no white space before a closing ")"
 789 | ERROR   | [x] Spaces must be used to indent lines; tabs are not allowed
 789 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 3
 789 | ERROR   | [x] TRUE, FALSE and NULL must be uppercase; expected "FALSE"
     |         |     but found "false"
 789 | ERROR   | [x] There should be no white space after an opening "("
 789 | ERROR   | [x] There should be no white space before a closing ")"
 790 | ERROR   | [x] Spaces must be used to indent lines; tabs are not allowed
 790 | ERROR   | [x] Line indented incorrectly; expected 4 spaces, found 3
 790 | ERROR   | [x] There should be no white space after an opening "("
 790 | ERROR   | [x] There should be no white space after an opening "("
 790 | ERROR   | [x] There should be no white space before a closing ")"
 790 | ERROR   | [x] There should be no white space after an opening "("
 790 | ERROR   | [x] There should be no white space before a closing ")"
 790 | ERROR   | [x] There should be no white space before a closing ")"
 792 | ERROR   | [x] Whitespace found at end of line
```

2024-08-28 17:21 UTC, adam-vessey commented on modules/islandora_image/src/Plugin/Action/GenerateImageDerivative.php
Number of things here, from https://github.com/Islandora/islandora/actions/runs/10498083873/job/29082307172?pr=904

```
FILE: ..._dir/modules/islandora_image/src/Plugin/Action/GenerateImageDerivative.php
--------------------------------------------------------------------------------
FOUND 5 ERRORS AND 1 WARNING AFFECTING 5 LINES
--------------------------------------------------------------------------------
 26 | ERROR   | [x] Whitespace found at end of line
 38 | ERROR   | [x] Inline comments must start with a capital letter
 38 | ERROR   | [x] Inline comments must end in full-stops, exclamation marks,
    |         |     question marks, colons, or closing parentheses
 49 | WARNING | [x] A comma should follow the last multiline array item. Found:
    |         |     ]
 77 | ERROR   | [x] Expected 1 blank line after function; 0 found
 78 | ERROR   | [x] The closing brace for the class must have an empty line
    |         |     before it
```

2024-08-28 17:21 UTC, adam-vessey commented on modules/islandora_image/src/Plugin/Action/GenerateImageDerivativeFile.php
Number of things here, from https://github.com/Islandora/islandora/actions/runs/10498083873/job/29082307172?pr=904

```
 FILE: .../modules/islandora_image/src/Plugin/Action/GenerateImageDerivativeFile.php
--------------------------------------------------------------------------------
FOUND 4 ERRORS AND 1 WARNING AFFECTING 4 LINES
--------------------------------------------------------------------------------
 66 | ERROR   | [x] Inline comments must start with a capital letter
 66 | ERROR   | [x] Inline comments must end in full-stops, exclamation marks,
    |         |     question marks, colons, or closing parentheses
 77 | WARNING | [x] A comma should follow the last multiline array item. Found:
    |         |     ]
 89 | ERROR   | [x] Expected 1 blank line after function; 0 found
 90 | ERROR   | [x] The closing brace for the class must have an empty line
    |         |     before it
```

2024-08-28 17:34 UTC, jasonhildebrand commented
> RE: coding standards, our CI runs: https://github.com/Islandora/islandora_ci/blob/859a92805dd8cb51646ce30cfc12f30452dbff5c/travis_scripts.sh#L16

Thanks, this is useful.

2024-09-10 23:03 UTC, jasonhildebrand commented
I've pushed a partial de-lint to run these and see if two of the files are now clean - more coming.

2024-09-11 14:59 UTC, jasonhildebrand commented on src/IslandoraUtils.php
> +
This is clean now - all checks passed.

2024-09-11 14:59 UTC, jasonhildebrand commented on modules/islandora_image/src/Plugin/Action/GenerateImageDerivative.php
This is clean now - all checks passed.

2024-09-11 15:00 UTC, jasonhildebrand commented on modules/islandora_image/src/Plugin/Action/GenerateImageDerivativeFile.php
This is clean now - all checks passed.

2025-08-12 13:18 UTC, closed without merging