Issue #964: Allow relative paths in IIIF manifests.
Islandora/islandora pull request #965
Opened 2023-07-11 02:34 UTC by alxp

**GitHub Issue**: [(link)](https://github.com/Islandora/islandora/issues/964)

# What does this Pull Request do?

Adds a configuration option for IIIF manifests to use relative paths for image URLs.

# What's new?

Adds a config option to make IIIF manifests use local file paths.
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? No

# How should this be tested?

On an Islandora site set up with Islandora IIIF and paged content, go to a piece of paged content, and's manifest URL, usually node/[node:nid]/book-manifest or .../manifest.

Note the image URLs under canvases > images > resources include URL encoded strings representing the full URL of the image, including the Drupal site host.

Go to the Admin settings page for Islandora IIIF, /admin/config/islandora/iiif

Check the 'Use relative paths' option and save the settings.

Reload the same manifest and inspect the @id elements under canvases > resources and note they don't include the full (encoded) url of the Drupal site but only the relative path.
# Documentation Status

* Does this change existing behaviour that's currently documented? No
* Does this change require new pages or sections of documentation? No
* Who does this need to be documented for?
* Associated documentation pull request(s): ___  or documentation issue ___ TK

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

If you want to test this fully including a Cantaloupe stack I can give an example site config and Cantaloupe properties file.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/committers

2023-07-28 16:46 UTC, rosiel requested changes

2023-07-28 16:46 UTC, rosiel commented on modules/islandora_iiif/config/schema/islandora_iiif.schema.yml
> +    label: 'Use relative paths in manifest.'
the type and label lines need to be indented.

2023-07-28 16:46 UTC, rosiel commented on modules/islandora_iiif/src/Form/IslandoraIIIFConfigForm.php
> +      '#description' => $this->t("Check this if your IIIF Server is configured to access files locally. If unchecked, the absolute URL will be given and the IIIF server will make requests to this sit
1 - put in an "advanced" group
2 - mention the need for Cantaloupe to be on the Drupal server.

2023-08-06 20:34 UTC, alxp commented
Fixed schema indentation and added Advanced field group as requested.

2023-08-07 13:34 UTC, rosiel approved these changes

2023-08-07 13:34 UTC, merged